### ISSUE TITLE
Sometimes the program is stopping and "broken sound" is going back for a few seconds.

### ISSUE THREAD

**Issue by Oreeeee** [Raymai97/VMAudioBack#1]
In most cases sound after installing this patch is working fine but sometimes this weird sound goes back and patch is going back to work after 1-5 seconds. Guest Windows Vista x64 SP2

**Comment by Raymai97** [comment]
Do you run this patch as Windows Service? Any specific scenario to trigger the weird sound?

**Comment by Oreeeee** [comment]
@Raymai97 No specific conditions and patch doesn't work on XP.

**Comment by Raymai97** [comment]
Please provide below info for affected guest OS (WinXP and Vista):
* Version of VMware Player/Workstation
* Patch Installation Method
* By "not working", do you mean, sound glitch still happen when the patch is running?
* Does sound glitch still exist while playing a sound file with Windows Media Player?

**Comment by Oreeeee** [comment]
@Raymai97 

XP: Windows Embedded POSready 2009 English
Vista: Enterprise, Ultimate SP2 Polish

-VMware Workstation Pro 16.1.1
-Extracting ZIP into c:\VMAudioBack, running Install service.bat, starting service in services.msc
-Sound glitch is still happening on XP, on Vista problem gets reduced but still sometimes happen.
-Same as above.

I recompiled VMAudioFixTray to .NET Framework 2.0, build passed but I haven't tested it yet, I might use it as temporary solution for Windows 2000 guests, for XP standard version works fine.

**Comment by Raymai97** [comment]
@Oreeeee 
1) Do you mean, you have 3 guest OS
- Windows 2000 (Professional SP4 English?)
- Windows XP Embedded POSready 2009  (English?)
- Windows Vista Enterprise/Ultimate SP2 Polish

2) VMAudioFixTray is working perfectly fine on "XP POSready 2009" and "Vista SP2"?
If you recompile to .NET 2.0, is it working OK for Windows 2000 too?

3) I was not explicit on "sound file type" so I will ask again here. If you play a "MP3" file in WIndows Media Player of XP and 2000, without running any patch, would you get sound glitch?

This tool is created to mimic "playing MP3 file in WMP" because in my case, VMware will sound OK when I do this, and I thought VMAudioFixTray was also doing similar thing. Please let me know if my understanding is incorrect.

**Comment by Raymai97** [comment]
I just installed XP POSready 2009 and found it is very minimal and didn't come with codec to play MP3 file.

Could you delete DISABLE_LOGGING, run VMAudioBack.exe and see if the log is showing MCI internal error?
![image](https://user-images.githubusercontent.com/3296077/115136089-efbe0380-a04f-11eb-941e-45e35cc0650b.png)

**Comment by Raymai97** [comment]
@Oreeeee I think I found the issue and solution. Could you try below file, extract and replace files in your XP POSready 2009 guest OS?

[20210418_P1.zip](https://github.com/Raymai97/VMAudioBack/files/6330659/20210418_P1.zip)

**Comment by Raymai97** [comment]
``

**Comment by Raymai97** [comment]
Hi @Oreeeee could you response on this issue?

**Comment by Oreeeee** [comment]
@Raymai97 Sorry, I forgot that I even made this issue, I will test this file today.

**Comment by Oreeeee** [comment]
@Raymai97 Okay, so my bootleg version of VMAudioFixTray compiled to .NET Framework 2.0 works, as well as this file that you attached. Could you push the source code of new version to GitHub to help people with the same problem? Thanks.

**Comment by Raymai97** [comment]
OK I have published new version.
Could I confirm with you that below guest OS are now OK with version 1.2?
* Windows 2000 (Professional English?)
* Windows Embedded POSready 2009 English
* Vista Enterprise, Ultimate SP2 Polish

**Comment by Oreeeee** [comment]
@Raymai97 I tested POSready 2009 English and Vista Ultimate SP2 Polish only, because I couldn't install WIndows 2000 on VMware, on POSready 2009 sound is finally fixed and on Vista sound is still broken but it is less annoying, maybe bug in Vista, not VMware.

**Comment by Raymai97** [comment]
I am confused. Earlier you said

>  I recompiled VMAudioFixTray to .NET Framework 2.0, build passed but I haven't tested it yet, I might use it as temporary solution for Windows 2000 guests

But now you said

> I couldn't install WIndows 2000 on VMware

??

And do you mean that no matter what program you used (v1.1 / v1.2 / VMAudioFixTray) all will still hit sound issue in Windows Vista VMware guest OS?

**Comment by Oreeeee** [comment]
@Raymai97 No matter what I use, I still have sound issues in Vista.

**Comment by Raymai97** [comment]
@Oreeeee OK, what about "I might use it as temporary solution for Windows 2000 guests" but then you said "I couldn't install WIndows 2000 on VMware"?

**Comment by Oreeeee** [comment]
@Raymai97 I need to try to install Windows 2000 multiple times to it to even work. It crashes before "Updating Start Menu elements" portion of the setup. Sometimes it may not crash but mostly crashes on it.
