### ISSUE TITLE
Doesn't work in latest VMWare version

### ISSUE THREAD

**Issue by bob12111** [Raymai97/VMAudioBack#2]
I'm running VMWare version 16.1.2 build 17966106, when I try running VMAudioBack, I get an error saying:

"MCI error 263 when opening a.mp3"

Even v1-2 does this.

**Comment by Raymai97** [comment]
Hi bob12111,

1) What Windows are you running in VMware?
Example: 32-bit Windows XP Professional SP3

2) Are you able to play MP3 file with Windows Media Player in your guest OS?

3) Could you try again after rename the file "SET_TIMER_RES_INSTEADD" to "SET_TIMER_RES_INSTEAD"?

**Comment by bob12111** [comment]
I'm using Windows XP Professional SP3, but it looks like I don't have Windows Media Player in my guest OS.

Renaming the file seems to have worked, so far...

**Comment by Raymai97** [comment]
Do you mean after renamed the file, the VMAudioBack runs properly and resolved the sound glitch issue?
If your XP does not have WMP, it is probably the N edition for Europe region.

![image](https://user-images.githubusercontent.com/3296077/120265872-70208700-c2d3-11eb-944f-14ad0333adbe.png)

**Comment by bob12111** [comment]
> 
> 
> Do you mean after renamed the file, the VMAudioBack runs properly and resolved the sound glitch issue?

Yes, that seems to be the case.  And mine is probably the N edition...

**Comment by Raymai97** [comment]
Nice to hear the issue resolved. I'm closing this.
