### ISSUE TITLE
Can't run Windows XP x64

### ISSUE THREAD

**Issue by TK50P** [Raymai97/VMAudioBack#6]
It doesn't work so I tried opened VMAudioBack.exe but it says:
![Screenshot 2023-08-16 174704](https://github.com/Raymai97/VMAudioBack/assets/127497974/8fbafe09-f8ff-4bf1-b249-b46b2689ac6a)
"MCI error 275 when opening a.mp3"
is a bug? or missing packages?

**Comment by Raymai97** [comment]
Hi @TK50P 

MCI error 275 means file not found. Please **extract all files** to a folder like "C:\VMAudioBack" before running VMAudioBack.exe.

**Comment by Raymai97** [comment]
Closed issue due to no response.
